version: '3.8'

services:
  todolist:
    image: todolist
    build:
      context: todo_list
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 80:80

volumes: 
 db:
